font_family      JetBrainsMono Nerd Font
font_size        11.0
cursor_shape     beam
cursor_trail 200
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 3
# Прозрачность
background_opacity 0.75
background #000000
foreground #ffffff
allow_remote_control yes

# Убираем рамки
window_padding_width 10
confirm_os_window_close 0
