# --- Конфигурация Fuzzel (Tokyo Night) ---

font=JetBrainsMono Nerd Font:size=12
prompt="❯  "
terminal=kitty
width=35
horizontal-pad=20
vertical-pad=15
inner-pad=10

[border]
width=1
radius=12

[colors]
background=000000ee
text=ffffffff
match=888888ff
selection=222222ff
selection-text=ffffffff
border=333333ff

[dmenu]
exit-immediately-if-empty=yes
